task_2 done
nikanor97/Android_KIS_2018 pull request #2
Opened 2018-11-29 21:55 UTC by nikanor97

2018-11-30 20:52 UTC, IvanShafran requested changes
Сейчас 9. Давай к Java Code style приведешь и будет 10

2018-11-30 20:52 UTC, IvanShafran commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
Java Code Style не такой. 
Название переменных, методов и полей: camelCase
Названия классов: CamelCase

2018-11-30 21:07 UTC, nikanor97 commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
Про кнопки понял. Вьюшки тоже CamelCase назвать?

2018-11-30 21:10 UTC, IvanShafran commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
В xml по-разному пишут. можно_так и можноТак.
В Java коде смотри тут: http://google.github.io/styleguide/javaguide.html
Всё кроме отступов в 2 пробела подходит

2018-11-30 21:14 UTC, nikanor97 commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
Понял, спасибо

2018-11-30 21:24 UTC, nikanor97 commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
@IvanShafran Обновил

2018-11-30 21:56 UTC, IvanShafran commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
Ну чёт не всё обновил. Названия методов с маленькой буквы должны быть

2018-11-30 23:16 UTC, nikanor97 commented on task2/app/src/main/java/com/example/nikan/task2/MainActivity.java
> +        Button btn_send_email = (Button)findViewById(R.id.button_send_email);
@IvanShafran Теперь все обновил

2018-12-01 14:49 UTC, IvanShafran approved these changes

2018-12-01 14:49 UTC, merged